version: '3.5'

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: api
    depends_on:
      - database
    environment:
      - WAIT_HOSTS=database:3306      # wait for database service to be ready first
      - WAIT_HOSTS_TIMEOUT=300        # timeout the waiting after 5 minutes have elapsed.
      - WEB_DOCUMENT_ROOT=/app/public
    image: custom-backend:latest
    tty: true
    ports:
      - "8080:80"
    networks:
      - app_default
    volumes:
      # root directory of the project
      - "./backend:/app"
      - "api_vendor:/app/vendor"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: webapp
    command: ["sh"]
    # depends_on:
    #   - backend
    image: custom-node:latest
    tty: true
    ports:
      - "3000:3000"
    networks:
      - app_default
    volumes:
      # root directory of the project
      - "./frontend:/var/www"
      - "webapp_node_modules:/var/www/node_modules"

  database:
    container_name: database
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1 # Should be disabled on production
      - MYSQL_USER=superuser
      - MYSQL_PASSWORD=supersecure
      - MYSQL_DATABASE=exercise
    expose:
      - "3306"
    image: mysql:8.0.23
    networks:
      - app_default
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - "app_dbdata:/var/lib/mysql"

networks:
  app_default:
volumes:
  api_vendor:
  # webapp_node_modules:
  app_dbdata:
